__base__: "baseconfig.yaml"
checkpoint:
  resume: false          # 是否从断点恢复
  resume_path: "/workspace/gan_seg/outputs/exp/20251010_202438beststable/checkpoints/step_14000.pt"
  save_every_iters: 1000
model:
  flow:
    name: "EulerFlowMLP"
    lr : 0.0001
    NSFP:
      num_layers: 8
      num_hidden: 128
      activation: "leakyrelu"
  mask:
    name: "EulerMaskMLPResidual"
    lr : 0.0001

    slot_num: 40
    use_normalization: false  # 启用normalization
    normalization_type: "group_norm"  # 使用group_norm节省内存
    MLP:
      num_layers: 9
      num_hidden: 128
dataset:
  name: "AV2Sequence"
  val_name: "AV2Sequence_val"

dataloader:
  batchsize: 1
  num_workers: 0

training:
  max_iter: 30000
  eval_loop: 100
  begin_train_smooth: 0
  begin_train_mask: 0

lr_multi:
  rec_loss: 1.0
  flow_loss: 0.0
  scene_flow_smoothness: 10
  rec_flow_loss: 0.0
  point_smooth_loss: 0.01
  eular_flow_loss: 0.01
  KDTree_loss: 1.0
  KNN_loss: 1.0
  l1_regularization: 0.0
  eular_mask_loss: 1

loss:
  scene_flow_smoothness:
    scale_flow_grad: 0.001
    each_mask_item:
      relative_gradient: 0.9
      criterion: "L2"
    sum_mask_item:
      relative_gradient: 0
      criterion: "L2"


vis:
  show_window: false
  debug_grad: false