# baseconfig.yaml
# This is a base configuration file that sets default values for various parameters.
log:
  name: "defaultname"
  dir: "" #default save to /output/exp
model:
  flow:
    name: "NSFP" # NSFP or OptimizedFlow
    NSFP:
      num_layers: 8
      num_hidden: 128
      activation: "relu"
  mask:
    name: "OptimizedMask"
    slot_num: 10


training:
  max_iter: 200

dataloader:
  batchsize: 1

lr_multi:
  rec_loss: 0.0
  flow_loss: 1
  scene_flow_smoothness: 1000
  rec_flow_loss: 0.01
  point_smooth_loss: 0.01

vis:
  show_window: false